version: '3'
services:
  nginx:
    build:
      dockerfile: dev.Dockerfile
      context: ./nginx
    depends_on:
      - frontend
      - backend
    ports:
      - '4040:80'
    restart: always
  frontend:
    build:
      dockerfile: dev.Dockerfile
      context: ./frontend
    volumes:
      - /app/node_modules
      - ./frontend:/app
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
  backend:
    stdin_open: true
    build:
      dockerfile: dev.Dockerfile
      context: ./backend
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./backend:/app